GET http://localhost:3000


###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route test 1",
  "source_id": "1",
  "destination_id": "2"
}


### Coisas do map

### Pegar o place_id
GET http://localhost:3000/places?text=av goias, goiania, 100
