GET http://localhost:3000


###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route test 1",
  "source_id": "1",
  "destination_id": "2"
}


### Coisas do map

### Pegar o place_id
GET http://localhost:3000/places?text=av rio verde, aparecida de goiania


### Pegar direções entre 2 pontos
GET http://localhost:3000/directions?originId=EjFBdi4gUmlvIFZlcmRlLCBBcGFyZWNpZGEgZGUgR29pw6JuaWEgLSBHTywgQnJhc2lsIi4qLAoUChIJaRTC-jj3XpMR1bHNaVz8GDwSFAoSCW05ybzU-16TEejkqLxazI4T&destinationId=ChIJjVBCCGLxXpMRqp30HMbmRqA